// app/surface/GrooveboxNav.tsx
import React from 'react';

interface GrooveboxNavProps {
  currentPage: string;
  onNavigate: (target: string) => void;
  songscribeRunning: boolean;
  songscribeCloned: boolean;
  songscribeUrl: string;
}

const NAV_ITEMS = [
  { id: 'composer', label: 'Compose', icon: 'bi-music-note-beamed' },
  { id: 'vault', label: 'Vault', icon: 'bi-folder2-open' },
  { id: 'library', label: 'Library', icon: 'bi-collection' },
  { id: 'songscribe', label: 'Songscribe', icon: 'bi-mic' },
  { id: 'overview', label: 'Status', icon: 'bi-activity' },
];

export function GrooveboxNav({
  currentPage,
  onNavigate,
  songscribeRunning,
  songscribeCloned,
  songscribeUrl,
}: GrooveboxNavProps) {
  return (
    <header className="groovebox-nav" aria-label="Main">
      <div className="groovebox-nav-top">
        <div className="groovebox-nav-brand">
          <button
            className="groovebox-nav-home"
            onClick={() => window.location.href = 'http://localhost:5173'}
            title="Back to UI Hub"
            aria-label="Back to UI Hub"
          >
            <i className="bi bi-house-door-fill" />
          </button>
          <span className="groovebox-nav-title">GrooveBox888</span>
        </div>
        <nav className="groovebox-nav-links" aria-label="Pages">
          {NAV_ITEMS.map(item => (
            <button
              key={item.id}
              className={`groovebox-nav-link${currentPage === item.id ? ' is-active' : ''}`}
              onClick={() => onNavigate(item.id)}
              title={item.id === 'songscribe' && !songscribeRunning ? 'Songscribe is offline' : item.label}
            >
              <i className={`bi ${item.icon} groovebox-nav-link-icon`} />
              <span className="groovebox-nav-link-label">{item.label}</span>
              {item.id === 'songscribe' && (
                <span className={`groovebox-nav-dot ${songscribeRunning ? 'dot-online' : 'dot-offline'}`} />
              )}
            </button>
          ))}
        </nav>
      </div>
    </header>
  );
}

export default GrooveboxNav;

// groovebox-vue/src/skills/molecules/GrooveboxNav.vue
<template>
  <header class="groovebox-nav" aria-label="Main">
    <div class="groovebox-nav-top">
      <div class="groovebox-nav-brand">
        <button
          class="groovebox-nav-home"
          @click="$emit('goHome')"
          title="Back to UI Hub"
          aria-label="Back to UI Hub"
        >
          &#x2302;
        </button>
        <span class="groovebox-nav-title">Groovebox</span>
      </div>
      <nav class="groovebox-nav-links" aria-label="Pages">
        <button
          v-for="item in navItems"
          :key="item.id"
          :class="['groovebox-nav-link', { 'is-active': currentPage === item.id }]"
          @click="$emit('navigate', item.id)"
          :title="item.id === 'songscribe' && !songscribeRunning ? 'Songscribe is offline' : item.label"
        >
          <span class="groovebox-nav-link-label">{{ item.label }}</span>
          <span
            v-if="item.id === 'songscribe'"
            :class="['groovebox-nav-dot', songscribeRunning ? 'dot-online' : 'dot-offline']"
          />
        </button>
      </nav>
      <button
        :class="['groovebox-nav-link', { 'is-active': filePickerOpen }]"
        @click="$emit('toggleFilePicker')"
        title="Toggle file picker sidebar"
        aria-label="Toggle file picker"
      >
        <span class="groovebox-nav-link-label">&#x1F4C1;</span>
      </button>
    </div>
  </header>
</template>

<script setup lang="ts">
defineProps<{
  currentPage: string;
  songscribeRunning: boolean;
  filePickerOpen: boolean;
}>();

defineEmits<{
  navigate: [page: string];
  toggleFilePicker: [];
  goHome: [];
}>();

const navItems = [
  { id: 'composer', label: 'Compose' },
  { id: 'vault', label: 'Vault' },
  { id: 'library', label: 'Library' },
  { id: 'songscribe', label: 'Songscribe' },
  { id: 'overview', label: 'Status' },
];
</script>
